### ISSUE TITLE
GAM figures put y-axis back on blue GAMS but not the title

### ISSUE THREAD

**Issue by mireillesavoie** [FundyPhytoPhys/prochlorococcus_o2#17]

**Comment by mireillesavoie** [comment]
There is a slight difference still because the y-axis text takes a little space away from the Red GAM plot. If it needs to be exact, I will have to put the y-axis text on the Blue GAM but make it colored white if the text is too much.

**Comment by NaamanOmar** [comment]
I can help. You need cowplot.

**Comment by mireillesavoie** [comment]
Used patchwork, it scales figures appropriately when common axis titles are removed
