### ISSUE TITLE
Correct README names in subfolders

### ISSUE THREAD

**Issue by NaamanOmar** [FundyPhytoPhys/prochlorococcus_o2#49]
GitHub will not understand your README you change the name of the README

**Comment by mireillesavoie** [comment]
Do you mean remove the ‘_Code’ from README_Code in the subfolder Code?
If so, Miranda should do the same because I followed her naming convention in Northumland …

**Comment by NaamanOmar** [comment]
Yes, I have corrected the filenames in NorthumberlandWaterQuality

**Comment by mireillesavoie** [comment]
Haha. I see how it now shows the readme .Thank you!
