### ISSUE TITLE
Role of PGP in DNA repair

### ISSUE THREAD

**Issue by NaamanOmar** [FundyPhytoPhys/prochlorococcus_o2#51]
I will read a little on this. We may have to remove the enzyme from the figure.

**Comment by NaamanOmar** [comment]
Figure 12 of the ROund 1 manuscript

**Comment by mireillesavoie** [comment]
Hi Naaman, Met with Doug today, he says remove this enzyme. It clears by products produced from DNA repair , not a DNA repair enzyme.

Thank you!

**Comment by NaamanOmar** [comment]
Done :)
